version: '3.3'
services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres
    command:
      - "postgres"
      - "-c"
      - "max_connections=1000"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=analytic
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - postgres
  monolith:
    container_name: monolith
    hostname: monolith
    image: monolith
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_USERNAME: postgres
    depends_on:
      - postgres
    networks:
      - postgres
      - triplan
    ports:
      - "8080:8080"
volumes:
  postgres-data:
networks:
  postgres:
  triplan: